//! # Rsift Optimized Graphics Engine (`rsift-opt-gfx`)
//!
//! Tier 1–6 rendering / CPU optimizations — adaptive per hardware tier.

pub mod chunk_mesh;
pub mod gpu_culling;
pub mod iris_pipeline;
pub mod gui_settings;
pub mod boot_splash;
pub mod eco_render;
pub mod binary_greedy_meshing;
pub mod vertex_pool;
pub mod mesh_cache;
pub mod cpu_occlusion;
pub mod leaf_fast_path;
pub mod render_pipeline;
pub mod software_tiling;
pub mod adaptive_shading;
pub mod lod_hybrid;
pub mod texture_budget;
pub mod render_graph;
pub mod section_rle;
pub mod hzb_2d;
pub mod chunk_cull;
pub mod noise_upsample;
pub mod persistent_vbo_pool;
pub mod packed4;
pub mod pull_mesh;
pub mod gpu_vertex_pull;
pub mod frame_reuse;
pub mod branchless_dda;
pub mod svo;
// Tier 1
pub mod material_batch;
pub mod texture_atlas;
pub mod gl33_compat;
pub mod ao_bake;
// Tier 2
pub mod diff_mesh;
pub mod triple_buffer;
// Tier 3
pub mod simd_kernels;
pub mod async_chunk_io;
pub mod soa_layout;
pub mod tick_render_split;
// Tier 4
pub mod drs;
pub mod depth_prepass;
pub mod billboard_lod;
// Tier 5
pub mod spatial_hash;
pub mod entity_tick_lod;
// Tier 6
pub mod light_cache;
pub mod taa;
pub mod occlusion_complete;
pub mod world_column_store;
pub mod low_spec_stack;
pub mod section_compress;

pub use chunk_mesh::*;
pub use gpu_culling::*;
pub use iris_pipeline::*;
pub use gui_settings::*;
pub use boot_splash::*;
pub use eco_render::*;
pub use binary_greedy_meshing::*;
pub use vertex_pool::*;
pub use mesh_cache::*;
pub use cpu_occlusion::*;
pub use leaf_fast_path::*;
pub use render_pipeline::*;
pub use software_tiling::*;
pub use adaptive_shading::*;
pub use lod_hybrid::*;
pub use texture_budget::*;
pub use render_graph::*;
pub use section_rle::*;
pub use chunk_cull::*;
pub use hzb_2d::*;
pub use noise_upsample::*;
pub use persistent_vbo_pool::*;
pub use packed4::*;
pub use pull_mesh::*;
pub use gpu_vertex_pull::*;
pub use frame_reuse::*;
pub use branchless_dda::*;
pub use svo::*;
pub use material_batch::*;
pub use texture_atlas::*;
pub use gl33_compat::*;
pub use ao_bake::*;
pub use diff_mesh::{DiffMeshUpdater, MeshPatch, SECTIONS_Y};
pub use triple_buffer::*;
pub use simd_kernels::*;
pub use async_chunk_io::*;
pub use soa_layout::*;
pub use tick_render_split::*;
pub use drs::*;
pub use depth_prepass::*;
pub use billboard_lod::*;
pub use spatial_hash::*;
pub use entity_tick_lod::*;
pub use light_cache::*;
pub use taa::*;
pub use occlusion_complete::*;
pub use world_column_store::*;
pub use low_spec_stack::*;
pub use section_compress::*;

// ---- New low-spec / integrated-GPU modules ----
// Registered with `pub mod` ONLY (no glob `pub use`): each module defines its
// own Vec3/Vec4 to avoid name collisions when re-exported.
pub mod aces_tonemap;
pub mod overdraw_sort;
pub mod half_vertex;
pub mod checkerboard;
pub mod vertex_cache_opt;
