//! build.rs — インストーラーへの **実バイナリ payload** 埋め込み。
//!
//! 旧 embedded_payloads は 148byte の MZ スタブ / マーカー文字列を「自己展開 DLL」
//! として偽装していた。本 build.rs は **実際にコンパイルされた成果物のみ** を
//! `include_bytes!` で埋め込み、見つからない payload は `None` (cargo:warning 明示)
//! とする。ダミー埋め込みは一切行わない。
//!
//! 探索順 (先着):
//!   1. `$RSIFT_PAYLOAD_DIR/<name>`                    (任意の明示指定)
//!   2. `<workspace>/target/<PROFILE>/<name>`          (通常の MSVC/GNU 単一ターゲット配置)
//!   3. `<workspace>/target/<triple>/<PROFILE>/<name>` (明示ターゲット配置)
//!   4. (jar のみ) `<workspace>/bootstrap/prebuilt/…`  (pack-jar.ps1 の実出力)

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// (生成定数名, 成果物ファイル名, 未検出時のビルド手順ガイダンス)
const PAYLOADS: [(&str, &str, &str); 5] = [
    (
        "PAYLOAD_RSGRAPHICS_DLL",
        "rsgraphics.dll",
        "cargo build --release -p rsgraphics",
    ),
    (
        "PAYLOAD_RSCALC_DLL",
        "rscalc.dll",
        "cargo build --release -p rscalc",
    ),
    (
        "PAYLOAD_RSREPLAY_DLL",
        "rsreplay.dll",
        "cargo build --release -p rsreplay",
    ),
    (
        "PAYLOAD_RSIFT_JVM_DLL",
        "rsift_jvm.dll",
        "cargo build --release -p rsift-jvm",
    ),
    (
        "PAYLOAD_BOOTSTRAP_JAR",
        "rsift-bootstrap.jar",
        "powershell -File bootstrap\\pack-jar.ps1 (要 JDK)",
    ),
];

/// 実 DLL/jar は数百 KB 〜 MB 級。これ未満は切り詰め/旧ダミーとみなし payload 不採用。
const MIN_PAYLOAD_BYTES: u64 = 2048;

fn candidate_paths(workspace: &Path, profile: &str, file: &str) -> Vec<PathBuf> {
    let mut v = Vec::new();
    if let Ok(dir) = env::var("RSIFT_PAYLOAD_DIR") {
        if !dir.is_empty() {
            v.push(Path::new(&dir).join(file));
        }
    }
    v.push(workspace.join("target").join(profile).join(file));
    for triple in ["x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu"] {
        v.push(workspace.join("target").join(triple).join(profile).join(file));
    }
    if file == "rsift-bootstrap.jar" {
        v.push(workspace.join("bootstrap").join("prebuilt").join(file));
        v.push(workspace.join("bootstrap").join(file));
    }
    v
}

fn main() {
    println!("cargo:rerun-if-env-changed=RSIFT_PAYLOAD_DIR");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("ワークスペースルート解決失敗 (crates/rsift-installer 配置前提)")
        .to_path_buf();
    let profile = env::var("PROFILE").unwrap_or_else(|_| "release".to_string());
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let mut gen = String::from(
        "// AUTO-GENERATED by rsift-installer/build.rs — 実 payload のみ (ダミー禁止)。\n",
    );
    let mut missing: Vec<(&str, &str)> = Vec::new();

    for (const_name, file, howto) in PAYLOADS {
        let cands = candidate_paths(&workspace, &profile, file);
        // 欠損パスも監視登録: 後から DLL が生成されれば build script が再実行され
        // payload が確実に埋め込まれる (cargo clean -p 不要の決定論的再埋め込み)。
        for c in &cands {
            println!("cargo:rerun-if-changed={}", c.display());
        }
        let found = cands.iter().find(|p| {
            p.is_file()
                && fs::metadata(p)
                    .map(|m| m.len() >= MIN_PAYLOAD_BYTES)
                    .unwrap_or(false)
        });
        match found {
            Some(p) => {
                // include_bytes! は Windows でも `/` 区切りを受理するため正規化して埋め込む。
                let fwd = p.to_string_lossy().replace('\\', "/");
                gen.push_str(&format!(
                    "pub(crate) const {c}: Option<&'static [u8]> = Some(include_bytes!(\"{p}\"));\n",
                    c = const_name,
                    p = fwd
                ));
            }
            None => {
                gen.push_str(&format!(
                    "pub(crate) const {c}: Option<&'static [u8]> = None;\n",
                    c = const_name
                ));
                missing.push((file, howto));
            }
        }
    }

    for (file, howto) in &missing {
        println!(
            "cargo:warning=[rsift-installer] payload 未埋め込み: {} — 先に `{}` を実行してから installer を再ビルドすること (実行時は該当 payload が fail-loud Err で無効化されます)",
            file, howto
        );
    }
    if missing.is_empty() {
        println!("cargo:warning=[rsift-installer] 全 5 payload の実埋め込みに成功");
    }

    fs::write(out_dir.join("payloads.rs"), gen).expect("payloads.rs 生成失敗");
}
