[package]
name = "rsift-opt-gfx"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "HZB GPU-driven culling, 12-byte quantized meshing, and Iris shader pipeline for Rsift"

[dependencies]
bytemuck.workspace = true
tracing.workspace = true
rayon.workspace = true
wgpu.workspace = true
zstd.workspace = true
lz4_flex.workspace = true
rsift-api = { path = "../rsift-api" }

[lib]
name = "rsift_opt_gfx"
crate-type = ["rlib"]
